// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIgxl0eYCoJz5O466J8g7Yxr1zA_yLuE',
    appId: '1:77403773311:web:894875c955da7ada85224a',
    messagingSenderId: '77403773311',
    projectId: 'weather-app-968c8',
    authDomain: 'weather-app-968c8.firebaseapp.com',
    storageBucket: 'weather-app-968c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrqYTTLP4Lur6VRhoMDEyhe8JqTzBm_zE',
    appId: '1:77403773311:android:0a217e9a53f5211e85224a',
    messagingSenderId: '77403773311',
    projectId: 'weather-app-968c8',
    storageBucket: 'weather-app-968c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0EBkdDMcHOsO7dgQ9Wa5iIQYaPrw0ws',
    appId: '1:77403773311:ios:5622f1fef7912c6385224a',
    messagingSenderId: '77403773311',
    projectId: 'weather-app-968c8',
    storageBucket: 'weather-app-968c8.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe0EBkdDMcHOsO7dgQ9Wa5iIQYaPrw0ws',
    appId: '1:77403773311:ios:5622f1fef7912c6385224a',
    messagingSenderId: '77403773311',
    projectId: 'weather-app-968c8',
    storageBucket: 'weather-app-968c8.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVIgxl0eYCoJz5O466J8g7Yxr1zA_yLuE',
    appId: '1:77403773311:web:6d7eff66d273ee3f85224a',
    messagingSenderId: '77403773311',
    projectId: 'weather-app-968c8',
    authDomain: 'weather-app-968c8.firebaseapp.com',
    storageBucket: 'weather-app-968c8.firebasestorage.app',
  );
}
